"""Description of changes

Revision ID: 0faac624b624
Revises: 
Create Date: 2024-10-31 12:36:43.141196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0faac624b624'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('text_content', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdf_documents_filename'), 'pdf_documents', ['filename'], unique=False)
    op.create_index(op.f('ix_pdf_documents_id'), 'pdf_documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pdf_documents_id'), table_name='pdf_documents')
    op.drop_index(op.f('ix_pdf_documents_filename'), table_name='pdf_documents')
    op.drop_table('pdf_documents')
    # ### end Alembic commands ###
