"""add signed_url column

Revision ID: 82f7c1b8a1ea
Revises: a33a40cf70ed
Create Date: 2025-06-08 20:35:38.627146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82f7c1b8a1ea'
down_revision: Union[str, None] = 'a33a40cf70ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdf_documents', sa.Column('signed_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pdf_documents', 'signed_url')
    # ### end Alembic commands ###
