"""Add file_url column

Revision ID: a33a40cf70ed
Revises: 0faac624b624
Create Date: 2025-06-06 01:02:01.767544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a33a40cf70ed'
down_revision: Union[str, None] = '0faac624b624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdf_documents', sa.Column('file_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pdf_documents', 'file_url')
    # ### end Alembic commands ###
